---
# This playbook uses the win_get_url module to download a simple HTML file for IIS
- name: Download simple web site 
  hosts: all 

  gather_facts: false
  tasks:
    - name: Download simple web site to 'C:\inetpub\wwwroot\TestSite'
      win_get_url:
        url: 'https://raw.githubusercontent.com/freezemist/Ansible-Test/master/IIS/index.html'
        dest: 'C:\inetpub\wwwroot\TestSite\index.html'