---
- name: Remove Default Web Site in IIS
  hosts: all 

  gather_facts: false
  tasks:
    - name: Remove Default Web Site in IIS
      win_iis_website:
      name: "Default Web Site"
      state: absent