---
# This playbook installs IIS and management tools, downloads and unzips, configures a website in IIS, then breaks the site by stopping a primary IIS Service

- name: Setup Test Site Break-Fix
  hosts: all
  gather_facts: false
  tasks:
    - name: Remove Default Web Site in IIS
      win_iis_website:
      name: "Default Web Site"
      state: absent
    - name: create website content directory
      win_file: path='c:\inetpub\wwwroot\TestSite' state=directory
    - name: Download simple web site to 'C:\inetpub\wwwroot\TestSite'
      win_get_url:
        url: 'https://raw.githubusercontent.com/freezemist/Ansible-Test/master/IIS/index.html'
        dest: 'C:\inetpub\wwwroot\TestSite\index.html'
    - name: Install IIS
      win_feature:
        name: "Web-Server"
        state: present
        restart: yes
        include_sub_features: yes
        include_management_tools: yes
    - name: IIS TestSite
      win_iis_website:
        name: "TestSite"
        state: started
        ip:  23.253.159.155
        port: 80
        application_pool: "TestSite"
        physical_path: c:\inetpub\wwwroot\TestSite\
      register: website